version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: vkbottle 
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata  # Use this if you want a bind mount
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vkbottle" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped  # Choose one restart policy
    tty: true
    stdin_open: true

    bot:
      build: .
      env_file:
        - .env
      depends_on:
        - db

  volumes:
    pgdata:
